export default {
  name: { type: String, required: true },
  x: { type: Number, required: true },
  y: { type: Number, required: true },
  direction: { type: String, required: true },
  world: { type: String, required: true },
  walking: { type: Boolean, default: false },
  spriteSheet: { type: String, required: true },
  heroClass: { type: String, required: true },
  experience: { type: Number, required: true },
  statsPoints: { type: Number, default: 0 },
  gold: { type: Number, default: 0 },
  level: { type: Number, default: 1 },
  stats: {
    type: {
      health: Number,
      maxHealth: Number,
      mana: Number,
      maxMana: Number,
      attack: Number,
      defense: Number,
      magic: Number,
      resistance: Number,
      speed: Number,
      dodge: Number,
    },
    default: {},
  },
  objects: { type: Array<String>, default: [] },
  stuffs: {
    type: {
      helmet: String || null,
      armor: String || null,
      weapon: String || null,
      shield: String || null,
      boots: String || null,
      gloves: String || null,
      pants: String || null,
    },
    default: {},
  },
  quests: { type: Array<String>, default: [] },
  skills: { type: Array<String>, default: [] },
};
